// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfuxjfgpqlbbohoyjpbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmdXhqZmdwcWxiYm9ob3lqcGJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjUzOTYsImV4cCI6MjA2ODk0MTM5Nn0.VMPkscCtoAmhVq5nUwzGHnym5hn7kYYJfKMihhPV0m0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});